version: "3.8"

volumes:
  pgdata: {}

services:
  db:
    image: postgres:16.3
    container_name: bun-hono-api-db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
