version: "3.8"

volumes:
  pgdata: {}
  redisdata: {}

services:
  db:
    image: postgres:16.3
    container_name: bun-hono-api-db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
  redis:
    image: bitnami/redis:7.2.5
    container_name: bun-hono-api-redis
    command: /opt/bitnami/scripts/redis/run.sh --appendonly no --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redisdata:/bitnami/redis/data
    env_file:
      - .env
